services:
  java_app:
    build:
      context: .
    container_name: "expensesapp"
    ports:
      - 8080:8080
    networks:
      - expenses-app-nw
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/expenses_tracker?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Test@123"
    depends_on:
      - mysql_db
    restart: always
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:8080 || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 60s

  mysql_db:
    image: mysql
    container_name: "mysql"
    ports:
      - "3306:3306"
    networks:
      - expenses-app-nw
    environment:
      MYSQL_ROOT_PASSWORD: "Test@123"
      MYSQL_DATABASE: "expenses_tracker"
    restart: always
    healthcheck:
      test: ["CMD-SHELL","mysqladmin ping -h localhost -uroot -pTest@123"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 60s
    volumes:
      - ./mysql-data:/var/lib/mysql


networks:
  expenses-app-nw:
volumes:
  mysql-data:
